import { readdirSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';

function generateLocalesEnum() {
  const messagesDir = join(process.cwd(), 'messages');
  const typesFile = join(process.cwd(), 'messages/types.ts');

  // Check if messages directory exists
  if (!existsSync(messagesDir)) {
    console.error(`Error: Messages directory not found at ${messagesDir}`);
    process.exit(1);
  }

  // Read all JSON files from messages directory
  let files: string[];
  try {
    files = readdirSync(messagesDir).filter((file) => file.endsWith('.json'));
  } catch (error) {
    console.error(`Error reading messages directory: ${error}`);
    process.exit(1);
  }

  // Extract locale codes from filenames
  const locales = files
    .map((file) => file.replace('.json', ''))
    .filter((locale) => locale.length > 0)
    .sort();

  if (locales.length === 0) {
    console.error('No locale files found in messages directory');
    process.exit(1);
  }

  // Generate the enum code
  const enumEntries = locales.map((locale) => `  ${locale} = "${locale}",`).join('\n');
  const enumCode = `// This file is autogenerated\n\nexport enum Locales {\n${enumEntries}\n}\n`;

  // Write the enum to types.ts file
  try {
    writeFileSync(typesFile, enumCode, 'utf-8');
    console.log(`✅ Generated Locales enum in messages/types.ts with ${locales.length} locales: ${locales.join(', ')}`);
  } catch (error) {
    console.error(`Error writing types.ts file: ${error}`);
    process.exit(1);
  }
}

generateLocalesEnum();
